# Generated by Django 5.2.6 on 2025-09-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_description',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='search_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_addresses',
            field=models.TextField(blank=True, help_text='Перечислите адреса магазинов через точку с запятой (;)', verbose_name='Адреса магазинов'),
        ),
    ]
